import { db } from '@/db';
import { storyCards } from '@/db/schema';

async function main() {
    const sampleStoryCards = [
        {
            title: 'Copenhagen: Carbon Neutral by 2025',
            subtitle: 'How Denmark\'s capital is leading the green transition',
            category: 'case-study',
            backgroundImage: 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800&h=600&fit=crop',
            linkUrl: '/case-studies/copenhagen-carbon-neutral',
            content: null,
            size: 'large',
            order: 0,
            published: true,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            title: 'Singapore Smart Nation Initiative',
            subtitle: 'Building the world\'s first smart nation through technology',
            category: 'case-study',
            backgroundImage: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800&h=600&fit=crop',
            linkUrl: '/case-studies/singapore-smart-nation',
            content: null,
            size: 'standard',
            order: 1,
            published: true,
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        {
            title: 'Barcelona Superblocks Revolution',
            subtitle: 'Reclaiming streets for people, not cars',
            category: 'case-study',
            backgroundImage: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800&h=600&fit=crop',
            linkUrl: '/case-studies/barcelona-superblocks',
            content: null,
            size: 'standard',
            order: 2,
            published: true,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            title: '68% of Global Population',
            subtitle: 'Will live in cities by 2050',
            category: 'data',
            backgroundImage: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800&h=600&fit=crop',
            linkUrl: null,
            content: 'The UN projects that 68% of the world\'s population will live in urban areas by 2050, up from 55% today. This rapid urbanization presents both challenges and opportunities for sustainable development.',
            size: 'medium',
            order: 3,
            published: true,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            title: '70% Reduction in Carbon Emissions',
            subtitle: 'Cities can achieve by 2030 with proper planning',
            category: 'data',
            backgroundImage: 'https://images.unsplash.com/photo-1569163139394-de4e4f43e4e5?w=800&h=600&fit=crop',
            linkUrl: '/data/carbon-reduction-potential',
            content: 'Research shows that cities can reduce their carbon emissions by up to 70% by 2030 through integrated urban planning, renewable energy adoption, and sustainable transportation systems.',
            size: 'standard',
            order: 4,
            published: true,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            title: 'Detroit Community Gardens',
            subtitle: 'Transforming vacant lots into thriving green spaces',
            category: 'action',
            backgroundImage: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=600&fit=crop',
            linkUrl: '/actions/detroit-community-gardens',
            content: null,
            size: 'standard',
            order: 5,
            published: true,
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },
        {
            title: 'Medellín Green Corridors',
            subtitle: 'How a Colombian city cooled down with nature',
            category: 'action',
            backgroundImage: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&h=600&fit=crop',
            linkUrl: '/actions/medellin-green-corridors',
            content: null,
            size: 'medium',
            order: 6,
            published: true,
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            title: 'Renewable Energy Cities',
            subtitle: 'Watch how cities worldwide are going 100% renewable',
            category: 'video',
            backgroundImage: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&h=600&fit=crop',
            linkUrl: 'https://www.youtube.com/watch?v=renewable-cities',
            content: null,
            size: 'standard',
            order: 7,
            published: true,
            createdAt: new Date('2024-01-28').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
        {
            title: 'The Urban Climate Challenge',
            subtitle: 'Cities consume 78% of global energy and produce 70% of emissions',
            category: 'big-picture',
            backgroundImage: 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1f?w=800&h=600&fit=crop',
            linkUrl: '/big-picture/urban-climate-challenge',
            content: null,
            size: 'standard',
            order: 8,
            published: true,
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        {
            title: '"Cities have the capability of providing something for everybody, only because, and only when, they are created by everybody."',
            subtitle: 'Jane Jacobs, Urban Planning Pioneer',
            category: 'quote',
            backgroundImage: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800&h=600&fit=crop',
            linkUrl: null,
            content: 'Jane Jacobs revolutionized urban planning by emphasizing the importance of community involvement in creating livable, sustainable cities. Her vision of inclusive urban development remains more relevant than ever as we face climate challenges.',
            size: 'standard',
            order: 9,
            published: true,
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-02-05').toISOString(),
        }
    ];

    await db.insert(storyCards).values(sampleStoryCards);
    
    console.log('✅ Story cards seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});