import { db } from '@/db';
import { storyCards } from '@/db/schema';

async function main() {
    const sampleStoryCards = [
        {
            title: 'Germany\'s Industry 4.0 Revolution',
            subtitle: 'How smart manufacturing transformed the automotive sector',
            category: 'case-study',
            backgroundImage: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&h=600',
            linkUrl: null,
            content: 'Germany\'s automotive industry has successfully implemented Industry 4.0 technologies, integrating IoT sensors, AI-driven predictive maintenance, and digital twins across manufacturing processes. Companies like BMW and Volkswagen have reduced production costs by 15% while improving quality control through smart factory implementations. The transformation includes real-time data analytics, automated supply chain management, and collaborative robots working alongside human workers. This digital transformation has positioned Germany as a global leader in smart manufacturing, creating thousands of high-skilled jobs and maintaining competitive advantage in the global automotive market.',
            size: 'large',
            order: 0,
            published: true,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            title: 'Singapore\'s Smart Nation Initiative',
            subtitle: 'Building the world\'s first smart nation through digital infrastructure',
            category: 'case-study',
            backgroundImage: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800&h=600',
            linkUrl: 'https://www.smartnation.gov.sg',
            content: null,
            size: 'medium',
            order: 1,
            published: true,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            title: 'Global R&D Investment Reaches $2.4 Trillion',
            subtitle: 'Innovation spending drives sustainable development worldwide',
            category: 'data',
            backgroundImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600',
            linkUrl: null,
            content: 'Global research and development expenditure has reached a record $2.4 trillion in 2023, representing 2.6% of global GDP. Leading countries include the United States ($680 billion), China ($550 billion), Japan ($170 billion), and Germany ($130 billion). Private sector investment accounts for 70% of total R&D spending, with significant increases in green technology, artificial intelligence, and biotechnology sectors. This investment has resulted in over 3.4 million patent applications globally, with renewable energy and digital infrastructure patents showing the highest growth rates at 25% annually.',
            size: 'standard',
            order: 2,
            published: true,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            title: 'Community Tech Hubs Drive Local Innovation',
            subtitle: 'Grassroots initiatives bridging the digital divide in rural areas',
            category: 'action',
            backgroundImage: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&h=600',
            linkUrl: null,
            content: 'Local communities across Africa, Asia, and Latin America are establishing technology hubs to provide digital skills training, internet access, and innovation spaces. These initiatives have created over 2,000 community tech centers, serving 15 million people in underserved areas. Programs include coding bootcamps, digital literacy courses, and startup incubation services. Success stories include Kenya\'s iHub network, India\'s Digital India Land Records modernization, and Colombia\'s rural connectivity projects. These grassroots efforts are crucial for inclusive industrialization and ensuring no one is left behind in the digital transformation.',
            size: 'medium',
            order: 3,
            published: true,
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },
        {
            title: 'Smart Manufacturing Revolution',
            subtitle: 'How AI and robotics are transforming production lines',
            category: 'video',
            backgroundImage: 'https://images.unsplash.com/photo-1565514020179-026b92b84bb6?w=800&h=600',
            linkUrl: 'https://www.youtube.com/watch?v=example-manufacturing',
            content: null,
            size: 'standard',
            order: 4,
            published: true,
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            title: 'The Future of Infrastructure is Digital',
            subtitle: 'Global trends shaping Industry 4.0 and smart cities',
            category: 'big-picture',
            backgroundImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800&h=600',
            linkUrl: null,
            content: 'Digital infrastructure investments are accelerating globally, with $7 trillion committed over the next decade. Key trends include 5G network expansion covering 85% of the global population by 2030, edge computing deployment reducing latency by 90%, and sustainable data centers powered by renewable energy. Smart city initiatives are being implemented in over 1,000 cities worldwide, integrating IoT sensors, AI analytics, and citizen engagement platforms. This digital transformation is creating new economic opportunities, improving quality of life, and enabling sustainable urban development patterns.',
            size: 'large',
            order: 5,
            published: true,
            createdAt: new Date('2024-01-28').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
        {
            title: 'Innovation is the bridge between dreams and reality',
            subtitle: 'Elon Musk, CEO of Tesla and SpaceX',
            category: 'quote',
            backgroundImage: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&h=600',
            linkUrl: null,
            content: 'This powerful quote from Elon Musk encapsulates the essence of SDG-09. Innovation serves as the critical link between ambitious sustainable development goals and tangible real-world solutions. Whether it\'s developing electric vehicles to reduce transportation emissions, creating reusable rockets to advance space technology, or building sustainable energy infrastructure, innovation transforms visionary ideas into practical applications that benefit humanity and the planet.',
            size: 'medium',
            order: 6,
            published: true,
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        {
            title: 'Denmark\'s Offshore Wind Success',
            subtitle: 'Leading the world in renewable energy infrastructure',
            category: 'case-study',
            backgroundImage: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=800&h=600',
            linkUrl: null,
            content: 'Denmark has become a global leader in offshore wind energy, generating 50% of its electricity from wind power. The country\'s innovative approach includes floating wind turbines, grid integration technologies, and green hydrogen production facilities. Major projects like Horns Rev and Ørsted\'s offshore installations have created 33,000 jobs and positioned Denmark as a technology exporter. The offshore wind sector contributes €15 billion annually to the Danish economy while reducing CO2 emissions by 12 million tons per year. This success demonstrates how sustainable infrastructure can drive economic growth and environmental progress simultaneously.',
            size: 'standard',
            order: 7,
            published: true,
            createdAt: new Date('2024-02-03').toISOString(),
            updatedAt: new Date('2024-02-03').toISOString(),
        },
        {
            title: '4.9 Billion People Still Lack Internet Access',
            subtitle: 'Bridging the global digital divide remains a critical challenge',
            category: 'data',
            backgroundImage: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&h=600',
            linkUrl: null,
            content: 'Despite significant progress in digital connectivity, 4.9 billion people worldwide still lack reliable internet access, with 96% living in developing countries. Rural areas face the greatest challenges, with only 37% coverage compared to 84% in urban areas. The economic impact is substantial: lack of digital infrastructure costs developing economies an estimated $2.5 trillion annually in lost GDP. However, initiatives like satellite internet constellations, community networks, and mobile infrastructure investments are rapidly expanding coverage. Closing this digital divide could lift 500 million people out of poverty by 2030.',
            size: 'standard',
            order: 8,
            published: true,
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-02-05').toISOString(),
        },
        {
            title: 'Corporate Innovation Labs Drive Change',
            subtitle: 'How companies are investing in sustainable technology development',
            category: 'action',
            backgroundImage: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?w=800&h=600',
            linkUrl: 'https://www.corporate-innovation-network.org',
            content: null,
            size: 'standard',
            order: 9,
            published: true,
            createdAt: new Date('2024-02-08').toISOString(),
            updatedAt: new Date('2024-02-08').toISOString(),
        },
        {
            title: 'High-Speed Rail Networks Transform Transportation',
            subtitle: 'Sustainable mobility infrastructure connects communities and economies',
            category: 'video',
            backgroundImage: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&h=600',
            linkUrl: 'https://www.youtube.com/watch?v=example-rail',
            content: null,
            size: 'medium',
            order: 10,
            published: true,
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        {
            title: 'Technology is best when it brings people together',
            subtitle: 'Matt Mullenweg, Founder of WordPress',
            category: 'quote',
            backgroundImage: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=800&h=600',
            linkUrl: null,
            content: 'Matt Mullenweg\'s insight highlights the social dimension of technological innovation. The most impactful infrastructure and industrial developments are those that connect communities, enable collaboration, and create inclusive opportunities for economic participation. From digital platforms that democratize access to information to transportation networks that link rural communities to urban markets, technology\'s greatest value lies in its ability to bring people together and create shared prosperity.',
            size: 'standard',
            order: 11,
            published: true,
            createdAt: new Date('2024-02-12').toISOString(),
            updatedAt: new Date('2024-02-12').toISOString(),
        }
    ];

    await db.insert(storyCards).values(sampleStoryCards);
    
    console.log('✅ Story cards seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});